apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  namespace: image
type: Opaque
data:
  azurestorageaccountname: Y3NnMTAwMzIwMDIzNDczYjAxNg==
  azurestorageaccountkey: SVJZK1VCNzYwVkQvalczajJ0cVVaeFJXb3RVTHRmZTlyR3JBeE1aLzNCRmNRb2xWU2l1bzNaS012eHdQOHdQOEtYRzUrb2U2MDJhMytBU3RDbmlTVEE9PQ==